### ISSUE TITLE
Add an "array strategy" for first 3 screens

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/mean-share-and-balance#334] opened 2024-07-31 21:39 UTC
Nancy noticed that when was trying to set the cup or plate values before they were visible, weird things happened (the default values overwrote the values she set, and some bars/apples became visible when they shouldn’t have). 

@marlitas @Nancy-Salpepi and I discussed this and would like to move ahead with this idea, which @arouinfar approved of: 

Create an "array strategy” (similar to kickDistributionStrategy) as a new element in the tree that lets the user set all cup/plate values, even if they aren’t visible. This would allow someone to pre-set all values for any screen even before they are visible. We would also change tableSnackNumberProperty to be read-only.

**Comment by Nancy-Salpepi** [comment] 2024-07-31 21:53
tagging https://github.com/phetsims/qa/issues/1121

**Comment by marlitas** [comment] 2024-08-02 00:19
This is ready for @amanda-phet to review.

**Comment by marlitas** [comment] 2024-08-12 17:33
I met with @amanda-phet and we found a way to reproduce:

1. Navigate to the Level Out Screen in Studio.
2. Set `meanShareAndBalance.levelOutScreen.model.initialWaterLevelsProperty` to:  [ 0.75,0.5,0,0.65,0.9,0.35,0.75] 
3. Add a third cup in the sim. Notice that the third cup is not a value of 0.

**Comment by marlitas** [comment] 2024-08-12 17:48
Due to a small oversight I was not iterating over all cups, only active cups which was causing the behavior. That should be fixed. @amanda-phet can you take a look now and make sure behavior is as expected? I can then mark for cherry-pick.

**Comment by amanda-phet** [comment] 2024-08-12 19:51
It's working! Thanks!

**Comment by marlitas** [comment] 2024-08-12 19:53
Great! Ready for cherry-pick.

**Comment by Nancy-Salpepi** [comment] 2024-08-14 20:30
The array strategies are working nicely! Closing.

**Closed by Nancy-Salpepi** 2024-08-14 20:30 UTC
Labels: dev:phet-io, status:ready-for-qa
