### ISSUE TITLE
CT Perennial task failed

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/mean-share-and-balance#99] opened 2022-08-24 16:39 UTC
```
mean-share-and-balance : build
Build failed with status code 1:
Running "report-media" task

Running "clean" task

Running "build" task
>> tsc complete: 102046ms
Building runnable repository (mean-share-and-balance, brands: phet, phet-io)
Building brand: phet
>> Webpack build complete: 23689ms
Fatal error: Perennial task failed:
AssertionError [ERR_ASSERTION]: Missing string information for mean-share-and-balance numberOfCupsProperty.link
at /data/share/phet/continuous-testing/ct-snapshots/1661298603378/chipper/js/grunt/getStringMap.js:213:11
at Array.forEach (<anonymous>)
at /data/share/phet/continuous-testing/ct-snapshots/1661298603378/chipper/js/grunt/getStringMap.js:201:15
at Array.forEach (<anonymous>)
at /data/share/phet/continuous-testing/ct-snapshots/1661298603378/chipper/js/grunt/getStringMap.js:200:23
at Array.forEach (<anonymous>)
at module.exports (/data/share/phet/continuous-testing/ct-snapshots/1661298603378/chipper/js/grunt/getStringMap.js:153:24)
at module.exports (/data/share/phet/continuous-testing/ct-snapshots/1661298603378/chipper/js/grunt/buildRunnable.js:138:21)
at async /data/share/phet/continuous-testing/ct-snapshots/1661298603378/chipper/js/grunt/Gruntfile.js:306:11
at async wrap (/data/share/phet/continuous-testing/ct-snapshots/1661298603378/chipper/js/grunt/Gruntfile.js:65:7)
Full Error details:
AssertionError [ERR_ASSERTION]: Missing string information for mean-share-and-balance numberOfCupsProperty.link
Snapshot from 8/23/2022, 5:50:03 PM
```

**Comment by samreid** [comment] 2022-08-24 20:23
The problem is that it thinks `simStrings.myStringProperty.link(...)` is a nested string named `link`.  @jonathanolson how can this be solved?

**Comment by zepumph** [comment] 2022-08-24 21:27
In my opinion it would be best to prohibit this usage instead of further complicating the the regex in getStringMap (used in the built to find the used string keys).

Is that acceptable to you? If so, we just need a way that this can error out way upstream of needing to build the sim to find out.

**Comment by samreid** [comment] 2022-08-25 00:32
@marlitas and I discussed that it would be unfortunate if our code has a `Property` that we are unable to call `link` or `unlink` or `debug` or `.value` on.  We also discussed that if more code had support to accept `Property<string>` arguments, like SCENERY/Text does, then our need to call those methods would be reduced.

**Comment by samreid** [comment] 2022-08-25 17:52
At today's meeting,

@pixelzoom reports that it would be helpful to link to the Property instances.
@jonathanolson says we can update the rule, so that if it detects something that ends with `StringProperty` then it will stop the regex search.  Or we could add an acceptable list of things like `link`, `unlink`, `.value` etc.  If we have a rule that no string keys contain the text `'StringProperty'` then we can use that rule.

**Comment by pixelzoom** [comment] 2022-08-27 21:12
Note that this is also preventing calls to (eg) `naturalSelectionStrings.addMutationProperty.value`, see https://github.com/phetsims/chipper/issues/1314.  That's not at all acceptable.  These are instances of `TReadOnlyProperty<string>`, and any of its API calls (include `link` and `get value`) should be usable.

**Comment by jonathanolson** [comment] 2022-08-31 20:26
This should be handled in https://github.com/phetsims/chipper/issues/1314, can you verify?

**Comment by KatieWoe** [comment] 2022-08-31 22:49
Looks ok in master, but master is pretty empty so I'll wait to close.

**Comment by pixelzoom** [comment] 2022-09-01 21:15
I confirmed that https://github.com/phetsims/chipper/issues/1314 is fixed. Back to @marlitas in case she has workarounds like https://github.com/phetsims/chipper/issues/1314#issuecomment-1229267567 that need to be removed.

**Comment by marlitas** [comment] 2022-09-21 23:31
Confirmed this workaround was removed. Closing.

**Closed by marlitas** 2022-09-21 23:31 UTC
Labels: type:automated-testing
