### ISSUE TITLE
Add sounds for the number of cups and the number of people on screens 1-3

### ISSUE THREAD

**Issue by Ashton-Morris** [phetsims/mean-share-and-balance#172] opened 2024-03-18 17:50 UTC
[I have two sounds here. ](https://o365coloradoedu.sharepoint.com/:f:/r/sites/PHYS-phet-pilot/PhET%20Files/PhET%20Files/PhET%20Sim%20Design/Mean_%20Share%20and%20Balance%20HTML5/Sounds%20and%20Sonification/Sound%20Files?csf=1&web=1&e=jhc6X1)

- MSaBNumberOfSelectionGlass.mp3
- MSaBNumberOfSelectionPlate.mp3

I have it mocked up to where it goes up one semi tone in pitch each time a plate or cup is added. I have a mockup of video of it in action.

[MSaBNumberOfSelectionVideoExample.mp4](https://o365coloradoedu.sharepoint.com/:f:/r/sites/PHYS-phet-pilot/PhET%20Files/PhET%20Files/PhET%20Sim%20Design/Mean_%20Share%20and%20Balance%20HTML5/Sounds%20and%20Sonification/Mockup%20Videos?csf=1&web=1&e=ntOfkA)

**Comment by marlitas** [comment] 2024-03-28 19:09
This has been added above, but I have a couple of implementation questions since it wasn't working with the NumberSpinner API as expected.

Over to @jbphet for review.

**Comment by jbphet** [comment] 2024-04-02 19:20
The initial versions of these have been added, here are the notes from the sound design review meeting (with @Ashton-Morris, @amanda-phet, and @marlitas):

- It sound like the sounds are being fired during reset, so we'll need to fix that.
- We're generally okay with the sound for the number of cups on the 1st screen but it has a bit too much of a bass thud to it, so @Ashton-Morris is going to try to take that out.  We'd also like to get @emily-phet's input.
- The sound for the plates on the 2nd and 3rd screen sounds a little to much like glass, so we'd like to get some alternatives for the next round.  Maybe more like plates on a wood table, potentially with a tablecloth.
- The pitch changes are sounding pretty good.

**Comment by Ashton-Morris** [comment] 2024-04-09 14:44
[I think I made an improvement to this sound. ](https://o365coloradoedu.sharepoint.com/sites/PHYS-phet-pilot/PhET%20Files/Forms/AllItems.aspx?csf=1&web=1&e=jhc6X1&cid=83d3c58c%2D3b8d%2D4e50%2D8ea6%2D9748dc2b6762&RootFolder=%2Fsites%2FPHYS%2Dphet%2Dpilot%2FPhET%20Files%2FPhET%20Files%2FPhET%20Sim%20Design%2FMean%5F%20Share%20and%20Balance%20HTML5%2FSounds%20and%20Sonification%2FSound%20Files&FolderCTID=0x0120001AF96E22694A1A448A9649A49C4AC974)


- MSaBNumberOfSelectionGlassV2.mp3

**Comment by Ashton-Morris** [comment] 2024-04-09 15:00
_"The sound for the plates on the 2nd and 3rd screen sounds a little to much like glass, so we'd like to get some alternatives for the next round. Maybe more like plates on a wood table, potentially with a tablecloth."_


I have also added these files to the link in the comment above. When you get the time @jbphet if you could set it up to where we can listen and compare them in the sim that would be great. 

- MSaBNumberOfSelectionPlateV4.mp3
- MSaBNumberOfSelectionPlateV3.mp3
- MSaBNumberOfSelectionPlateV2.mp3

**Comment by jbphet** [comment] 2024-04-09 17:28
We reviewed the most recent set of possible sounds in the 4/9/2024 design meeting, and have decided to try another round where the sounds have a bit more of the table and less of the china ringing out.  @Ashton-Morris will create these, and @jbphet or @marlitas will integrate and set up a query parameter so that they can be compared in situ.

**Comment by Ashton-Morris** [comment] 2024-04-10 22:27
I have recorded some variations of ceramic plates softly on a table, on a napkin on a table, and my hand. I hope that these suit it much better than yesterdays examples. [Link here](https://o365coloradoedu.sharepoint.com/sites/PHYS-phet-pilot/PhET%20Files/Forms/AllItems.aspx?csf=1&web=1&e=jhc6X1&cid=83d3c58c%2D3b8d%2D4e50%2D8ea6%2D9748dc2b6762&RootFolder=%2Fsites%2FPHYS%2Dphet%2Dpilot%2FPhET%20Files%2FPhET%20Files%2FPhET%20Sim%20Design%2FMean%5F%20Share%20and%20Balance%20HTML5%2FSounds%20and%20Sonification%2FSound%20Files&FolderCTID=0x0120001AF96E22694A1A448A9649A49C4AC974)

MSaBNumberOfSelectionPlateV7.mp3
MSaBNumberOfSelectionPlateV6.mp3
MSaBNumberOfSelectionPlateV5.mp3

**Comment by jbphet** [comment] 2024-04-11 21:14
I've integrated the 3 new sounds and removed the previous one.  There is now a query parameter `plateSound` that can take values of 0, 1, or 2 to select the sound.  For example, on my local system it looks like this:

```
http://localhost:8080/mean-share-and-balance/mean-share-and-balance_en.html?brand=phet&ea&debugger&plateSound=2
```

These sounds all seem like a big improvement, and I think we should be able to choose from these.  Assigning to @amanda-phet, @Ashton-Morris, @marlitas, and @emily-phet to try these out on main and log their opinions prior to the next review meeting.

I'd say my fave is `plateSound=1` because it has a little bit of tone to it without too much ring, but I'd honestly be happy with any of them.

**Comment by emily-phet** [comment] 2024-04-16 15:43
If I'm hearing what was intended...1 and 2 sound like nice UI sounds, but only the original actually has a "plate" quality to it for me (though feels a bit muffled in general). In the interest of time and resources, I think we should pick one of these and proceed, but it has lost its plate/table mapping for me.

**Comment by jbphet** [comment] 2024-04-16 17:15
We reviewed these sounds in the 4/16/2024 sound design meeting and have decided to go with `plateSound=1`.  I'll make this change and remove the query parameter.

**Comment by jbphet** [comment] 2024-04-17 21:04
Plate sound finalized.  Closing, though some mixing of sounds and other last minute changes may still occur in the final review phase.

**Closed by jbphet** 2024-04-17 21:04 UTC
Labels: design:sound, status:ready-for-review
