### ISSUE TITLE
Not always able to predict mean on the Distribute screen 

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/mean-share-and-balance#296] opened 2024-06-14 20:51 UTC
This is a behavior question, I am not sure if it is a bug. To observe:

1) Got to distribute screen
2) Enable "Predict Mean"
3) Drag the pencil up and down.

There is no position where the mean displays a success. If this is the expected behavior, feel free to close.

For #270.

**Comment by jessegreenberg** [comment] 2024-06-14 20:55
The code indicates that you should only be able to observe successes if the snacks are distributed, so maybe this is an intentional part of the model:

https://github.com/phetsims/mean-share-and-balance/blob/9fa448c5f7761c04b1776e36492a414a4ee68497/js/distribute/view/DistributeScreenView.ts#L211-L216

**Comment by marlitas** [comment] 2024-06-15 23:10
Yes, this is the expected behavior. I'll go ahead and assign to @amanda-phet since it was a question about behavior. Not sure if necessary to do anything about it, but want to make sure she is aware that it came up. Feel free to close if you want to leave as is.

**Comment by amanda-phet** [comment] 2024-06-16 00:37
Yes this is intentional. If you place the line you are just making a prediction. This seemed clear in interviews so I think it's fine to keep as-is.

**Closed by amanda-phet** 2024-06-16 00:37 UTC
Labels: design:general, dev:code-review
