### ISSUE TITLE
Notebook paper lines and water reference lines are hard to distinguish

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/mean-share-and-balance#120] opened 2022-10-10 19:25 UTC
On the water screen, when the 3D cups are set and the share button to open valves is activated, the 2D cups level themselves to the mean. The reference lines on the 2D cups (cup water level) to show where the water level is in the 3D cups is blending in with the notebook lines in the background. 
<img width="715" alt="image" src="https://user-images.githubusercontent.com/109630002/194938633-970fe7ee-2227-495f-951b-8eea808b9dd7.png">

**Comment by amanda-phet** [comment] 2022-10-10 20:32
I agree this is problematic... Ugh. Not sure what to do! I'm starting to think the notebook lines are doing more harm than good. I know we discussed changing the line spacing to line up with the tick marks, but this issue seems like it would still need addressing. I might want to try notebook paper with no lines and see how that feels.

**Comment by amanda-phet** [comment] 2022-10-11 18:36
Looks like this is a duplicate of https://github.com/phetsims/mean-share-and-balance/issues/111 so I"ll put my comment there and close this.

**Closed by amanda-phet** 2022-10-11 18:36 UTC
Labels: design:artwork, design:general
