### ISSUE TITLE
Fulcrum cueing arrows missing in launched sim

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/mean-share-and-balance#340] opened 2024-08-01 20:15 UTC
**Test device**
MacBook Air M1 chip

**Operating System**
14.5

**Browser**
Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/1121, in Studio/State wrappers on the Balance Point Screen: 
The launched/downstream sim will be missing the fulcrum's cueing arrows if the fulcrum was moved in studio/upstream sim.

This was also present in 1.1.0-dev.7

**Steps to reproduce**
1. In the state wrapper, set state rate = 0
2. In the upstream sim go to the Balance Point Screen and kick a ball
3. Move the fulcrum
4. Press Set State Now

**Visuals**
<img width="474" alt="Screenshot 2024-08-01 at 3 58 27 PM" src="https://github.com/user-attachments/assets/9229d43c-b3bf-4183-aac3-d5cb4989abf3">

**Comment by marlitas** [comment] 2024-08-05 22:31
Done above. Ready to cherry-pick.

**Comment by KatieWoe** [comment] 2024-08-14 21:18
This seems mostly fixed. If the bottom sim has moved the fulcrum, the cue arrows don't show up until you hit reset all. But this is rather minor.

**Comment by marlitas** [comment] 2024-08-14 21:41
> If the bottom sim has moved the fulcrum, the cue arrows don't show up until you hit reset all.

That sounds like expected behavior!

**Comment by KatieWoe** [comment] 2024-08-14 21:45
Closing then

**Comment by marlitas** [comment] 2024-08-20 17:33
Mmmm... that's a good question. My understanding is that cue indicators should not be stateful. So in the scenario you described I understand why the code is behaving that way, but I'm 1. not sure how to fix it, and 2. not sure if we want to fix it?

If the sim was starting from scratch the cueing arrows would appear, but since the state wrapper is just layering one state onto another, the downstream sim is remembering that the item was interacted with even though a new state was now applied.

I'm going to pose that question in the phet-io slack channel.

**Comment by marlitas** [comment] 2024-08-20 18:08
In slack @zepumph responded: 

> Seems totally reasonable to be unstateful. QA is very good at reporting discrepancies in the state wrapper. That doesn't mean that it all needs to be added. We center around the philosophy that "transient" items are not stateful. Cues seem very reasonable to be part of that. In the end it is up to the MSaB design team to determine if it is valuable to be stateful.

@jbphet and I also agree and this can be closed.

**Closed by marlitas** 2024-08-20 18:08 UTC
Labels: type:bug, dev:phet-io, status:ready-for-qa

**Comment by kathy-phet** [comment] 2024-08-20 21:25
@marlitas @jbphet @amanda-phet - 

I saw the dialog in Slack on this question, and it prompted me to look at CAV behavior. While the cuing arrows go away after moving the balls there is a property called soccerBallHasBeenDragged that you can toggle in studio. In this way, you can set the balls as you desire (which removes the cuing arrow), but then toggle this property to restore the cuing arrow so when launched the sim will start up in that state with the cuing arrow for the student to see. 

It seems like with the current behavior of mean share and balance you cannot configure in Studio and also have it launch with the cuing arrows, because it will always think the student has moved something. Just wanted to comment that the structure in CAV seems like a better pattern, so the instructional designer can reinstate the cuing after they do their design. 

![image](https://github.com/user-attachments/assets/d1b5a515-8914-474f-89b0-189c8c902396)

**Comment by kathy-phet** [comment] 2024-08-20 21:26
I'm not sure if its necessary in this case, since you can set the stacks of candy bars exactly. Just wanted to mention this pattern and its difference.

**Comment by marlitas** [comment] 2024-08-20 21:53
@kathy-phet I'm not seeing the behavior you're describing. I was told that cueing indicators are not stateful in general and we have that same pattern applying to the soccer balls in MSaB (and now CAV as well). If you drag a ball in studio and then launch a wrapper the cues will still appear until a student then moves something. 

The same thing will happen with the candy bars.

**Comment by marlitas** [comment] 2024-08-20 21:55
It seems rather buggy to me that the `soccerBallHasBeenDraggedProperty` is not readonly. I'm not sure why we need to expose that to a client. It's not a matter of opinion, rather a fact of wether something has been dragged in the sim or not. I also believe that the published CAV behavior/studio tree is probably quite different from what is on main now due to  groupSortInteraction.

**Comment by kathy-phet** [comment] 2024-08-20 22:36
I see - in the published version of CAV, the cueing indicator would not be there when you launched after setting up in Studio, unless I toggled it. The behavior on main looks good to me too.
