### ISSUE TITLE
Interactive highlight changes size

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/mean-share-and-balance#124] opened 2022-11-02 18:24 UTC
**Test device**
MacBook Air (m1 chip)

**Operating System**
macOS 13.0

**Browser**
Safari 16.1

**Problem description**
For https://github.com/phetsims/qa/issues/848, the interactive highlight around a valve changes size when the valve is open and closed. This doesn't happen when using the keyboard.

**Steps to reproduce**
1. Turn on interactive highlights
2. Open and close a valve

**Visuals**

https://user-images.githubusercontent.com/87318828/199571373-a08abbe3-af7a-490f-ad13-df6648c0078c.mp4

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Mean: Share and Balance‬
URL: https://phet-dev.colorado.edu/html/mean-share-and-balance/1.0.0-rc.1/phet/mean-share-and-balance_all_phet.html
Version: 1.0.0-rc.1 2022-11-01 17:03:54 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Safari/605.1.15
Language: en-US
Window: 1328x702
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by jessegreenberg** [comment] 2022-11-08 19:38
This is caused by this line:

```js
    // interactive highlighting - set a custom highlight because the pipe nodes have a unique combined highlight
    // collectively in the ScreenView
    this.interactiveHighlight = new FocusHighlightFromNode( this );

```

If we don't like the look of this we can create a different highlight. There are a few ways to do that and we can decide what looks best, @marlitas and I are meeting this afternoon to improve it.

**Comment by marlitas** [comment] 2022-11-08 23:26
This was fixed in the above commit and should be on master. @Nancy-Salpepi can you double check?

**Comment by Nancy-Salpepi** [comment] 2022-11-09 12:52
Looks good on master @marlitas!

**Comment by KatieWoe** [comment] 2022-11-11 20:30
Looks good in RC 2

**Closed by KatieWoe** 2022-11-11 20:30 UTC
Labels: type:bug, status:ready-for-review
