### ISSUE TITLE
Changes to maxPlatesProperty causes incorrect apple amounts in Standard PhET-iO wrapper

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/mean-share-and-balance#341] opened 2024-08-02 13:46 UTC
**Test device**
MacBook Air M1 chip

**Operating System**
14.5

**Browser**
Safari/Firefox

**Problem description**
For https://github.com/phetsims/qa/issues/1121, in Studio on the Fair Share Screen: 
Launching the sim with "collect" selected after changing the `maxPlatesProperty` results in the wrong number of apples displayed on the notepad.

**Steps to reproduce**
1. In studio, go to the Fair Share Screen
2. Change `meanShareAndBalance.fairShareScreen.model.maxPlatesProperty` to 3
3. Press the Collect button
4. Check the Total checkbox
5. Press Test--total is correct but the number of apples displayed is incorrect
6. Press the Sync button--each person has twice as many apples as they should

**Visuals**

https://github.com/user-attachments/assets/3e915a26-c1c8-4085-be07-d19d4f36949a

**Comment by marlitas** [comment] 2024-08-05 19:14
We also can get some weird states in the Distribute Screen:

<img width="1221" alt="image" src="https://github.com/user-attachments/assets/c6940882-ce13-480f-8cf6-f7b953852be3">

**Comment by Nancy-Salpepi** [comment] 2024-08-05 19:27
@marlitas what steps did you take to get https://github.com/phetsims/mean-share-and-balance/issues/341#issuecomment-2269739932 ?

**Comment by marlitas** [comment] 2024-08-05 19:36
@Nancy-Salpepi I added steps to reproduce above.

**Comment by marlitas** [comment] 2024-08-05 19:54
I know the problem, and unfortunately one screen can be handled without relying on `isSettingPhetioStateProperty` while the other screen cannot. This patch is a minimal `isSettingPhetioStateProperty` dependency. It makes the Fair Share screen more robust in it's handling of the `resetData` function, however I'm not sure if it's worth it since we can't do the same in the Distribute Screen.

I'm torn and not sure what fix to commit... Here is a patch that makes Fair Share more robust and minimizes the dependency on said Property. The other strategy doesn't need a patch... it's a pretty straightforward code change. I would like another devs opinion before deciding which way to go.

<details>

```diff
Subject: [PATCH] phet-io state handling
---
Index: js/common/model/SharingModel.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/model/SharingModel.ts b/js/common/model/SharingModel.ts
--- a/js/common/model/SharingModel.ts	(revision e4f21c5058c39242290abd7e10512f6d61c05d39)
+++ b/js/common/model/SharingModel.ts	(date 1722887412427)
@@ -28,6 +28,7 @@
 import Fraction from '../../../../phetcommon/js/model/Fraction.js';
 import VoidIO from '../../../../tandem/js/types/VoidIO.js';
 import ArrayIO from '../../../../tandem/js/types/ArrayIO.js';
+import isSettingPhetioStateProperty from '../../../../tandem/js/isSettingPhetioStateProperty.js';
 
 type SelfOptions = {
 
@@ -289,14 +290,6 @@
   protected resetData(): void {
     this.numberOfPlatesProperty.reset();
 
-    // Release all snack from plates by setting their table snack number to 0.  This puts the snacks back onto the
-    // unused list so that when the plates are reset, they can grab the ones they need the same way they did during
-    // construction of the model.
-    this.plates.forEach( plate => { plate.tableSnackNumberProperty.value = 0; } );
-
-    // Reset the active plates, whereupon they will grab and position snacks to match their initial table snack number.
-    this.plates.forEach( plate => plate.isActiveProperty.value && plate.reset() );
-
     // The maximum number of plates should still be respected after reset.
     const max = this.maxPlatesProperty.value;
     this.numberOfPlatesProperty.value = Math.min( this.numberOfPlatesProperty.value, max );
Index: js/fair-share/model/FairShareModel.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/fair-share/model/FairShareModel.ts b/js/fair-share/model/FairShareModel.ts
--- a/js/fair-share/model/FairShareModel.ts	(revision e4f21c5058c39242290abd7e10512f6d61c05d39)
+++ b/js/fair-share/model/FairShareModel.ts	(date 1722887412437)
@@ -572,6 +572,35 @@
   protected override resetData(): void {
     this.finishInProgressAnimations();
     this.appleDistributionModeProperty.reset();
+
+    // Release all snack from plates by setting their table snack number to 0.  This puts the snacks back onto the
+    // unused list so that when the plates are reset, they can grab the ones they need the same way they did during
+    // construction of the model.
+    let totalNumberOfSnacksOnPlates = 0;
+    this.plates.forEach( plate => {
+      totalNumberOfSnacksOnPlates += plate.tableSnackNumberProperty.value;
+      plate.tableSnackNumberProperty.value = 0;
+    } );
+
+    // With PhET-iO we cannot guarantee the apple distribution mode will be set to SYNC, so we need to handle
+    // each case individually.
+    if ( this.appleDistributionModeProperty.value === DistributionMode.COLLECT ) {
+      while ( this.appleCollection.length < totalNumberOfSnacksOnPlates ) {
+        const snack = this.getUnusedSnack();
+        assert && assert( snack, 'there should be enough snacks to populate the collection' );
+        this.appleCollection.push( snack! );
+      }
+    }
+    else if ( this.appleDistributionModeProperty.value === DistributionMode.SHARE ) {
+      this.getActivePlates().forEach( plate => {
+        plate.setNotepadSnacksToValue( new Fraction( totalNumberOfSnacksOnPlates, this.numberOfPlatesProperty.value ) );
+      } );
+    }
+    else if ( this.appleDistributionModeProperty.value === DistributionMode.SYNC ) {
+
+      // Reset the active plates, whereupon they will grab and position snacks to match their initial table snack number.
+      this.getActivePlates().forEach( plate => plate.reset() );
+    }
     super.resetData();
   }
 
Index: js/distribute/model/DistributeModel.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/distribute/model/DistributeModel.ts b/js/distribute/model/DistributeModel.ts
--- a/js/distribute/model/DistributeModel.ts	(revision e4f21c5058c39242290abd7e10512f6d61c05d39)
+++ b/js/distribute/model/DistributeModel.ts	(date 1722886738721)
@@ -329,7 +329,21 @@
   }
 
   protected override resetData(): void {
-    this.syncData();
+
+    // We may not want to sync the data if we are setting PhET-iO state. In that case we will rely on the state that
+    // PhET-iO has set for us.
+    if ( !isSettingPhetioStateProperty.value ) {
+      this.syncData();
+
+      // Release all snack from plates by setting their table snack number to 0.  This puts the snacks back onto the
+      // unused list so that when the plates are reset, they can grab the ones they need the same way they did during
+      // construction of the model.
+      this.plates.forEach( plate => { plate.tableSnackNumberProperty.value = 0; } );
+
+      // Reset the active plates, whereupon they will grab and position snacks to match their initial table snack number.
+      this.getActivePlates().forEach( plate => plate.reset() );
+    }
+
     super.resetData();
   }
 
```

</details>

**Comment by marlitas** [comment] 2024-08-05 21:02
I asked a question in slack and got the response from @samreid: 

> Hard to say without more seeing more context. But having 2x subclasses symmetrically respect `isSettingPhetioStateProperty` sounds ok. We have 134 usages of `isSettingPhetioStateProperty` and no plans to eliminate them.

This was already what I was leaning towards, so I went ahead an committed the fix above that just adds a dependency on `isSettingPhetioStateProperty` in super. It simplifies the code and unifies the subclass implementation. 

This also is now explicitly stating the assumption that during reset we should be in a "synced" state. If at any point the `DistributionModeProperty` were to change it's initial value the sim would not support that. I think it would be good for @jbphet to review once he is back.

**Comment by jbphet** [comment] 2024-08-12 22:37
I verified the two problematic use cases reported above on main, and they appear to be be fixed.

I'm fine with this use of `isSettingPhetioStateProperty.value`.  Seems like a necessary evil.

I have a few comments on the changes:
- In `FairShareModel.resetData`, there is a comment about resetting the mode to "sync".  This is also mentioned in [a comment above](https://github.com/phetsims/mean-share-and-balance/issues/341#issuecomment-2269912381).  If it is a requirement that the initial state is "sync", there should be an assertion to test this and a bit of an explanation as to why this is required.
- There is an override of `resetData` in `DistributeModel` that doesn't seem to do anything.  Can it be removed, or was something omitted?
- I know the `resetData` method has been around for a while and didn't change while addressing this issue, but the name is striking me as vague and potentially problematic for maintenance.  For instance, `SharingModel.reset` currently looks like this:
  ```js
    public reset(): void {
      this.meanInfoPanelVisibleProperty.reset();
      this.totalVisibleProperty.reset();
      this.resetData();
    }
  ```
  ...but why aren't the first two Properties considered "data"?  Is there a name that would make this distinction more clear, such as `resetPlateStates`?

Back to @marlitas for next steps.

**Comment by marlitas** [comment] 2024-08-13 02:40
> If it is a requirement that the initial state is "sync", there should be an assertion to test this and a bit of an explanation as to why this is required.

I added an assertion and documentation. @jbphet let me know if that is enough or needs more clarity.

> There is an override of resetData in DistributeModel that doesn't seem to do anything. Can it be removed, or was something omitted?

It can be removed. Thanks!

> but why aren't the first two Properties considered "data"? Is there a name that would make this distinction more clear, such as resetPlateStates or resetPlates?

I think I would be more open to renaming if we weren't in RC right now... The reason I don't see `meanInfoPanelVisibleProperty` or `totalVisibleProperty` as data is because these Properties are just booleans that determine wether something is visible or not. They are not directly affecting model calculations and therefore have nothing to do with the underlying data that is powering the model logic of the sim. 

If you feel really strongly about renaming we can talk more about it, but my instinct is to leave as is right now.

Overall I think this issue is ready for cherry-pick.

**Comment by marlitas** [comment] 2024-08-13 16:31
@jbphet and I talked this over and we are good to go. Thanks!

**Comment by KatieWoe** [comment] 2024-08-14 18:56
Looks fixed in rc.2

**Closed by KatieWoe** 2024-08-14 18:56 UTC
Labels: type:bug, dev:phet-io, status:ready-for-qa
