### ISSUE TITLE
Add a filtered chord sound to the water balance section on screen one

### ISSUE THREAD

**Issue by Ashton-Morris** [phetsims/mean-share-and-balance#171] opened 2024-03-18 17:34 UTC
I have two files incase it doesn't loop as well as an .mp3. I will be storing all audio files [in this folder here.](https://o365coloradoedu.sharepoint.com/:f:/r/sites/PHYS-phet-pilot/PhET%20Files/PhET%20Files/PhET%20Sim%20Design/Mean_%20Share%20and%20Balance%20HTML5/Sounds%20and%20Sonification/Sound%20Files?csf=1&web=1&e=qaXh1o)

- MSaBWaterBalanceFluteChordLoop.mp3
- MSaBWaterBalanceFluteChordLoop.wav

Here is a video mockup of how it sounds in action.

[MSaBWaterBalanceVideoExample.mp4](https://o365coloradoedu.sharepoint.com/:f:/r/sites/PHYS-phet-pilot/PhET%20Files/PhET%20Files/PhET%20Sim%20Design/Mean_%20Share%20and%20Balance%20HTML5/Sounds%20and%20Sonification/Mockup%20Videos?csf=1&web=1&e=2TfNly)

I have a low pass filter on the chord with a slight resonance or q on the filter. 

I also have the pitch or playback speed mapped to the eventual balance.  So if the balance is more full the chord is higher pitched and if it is lower in the glasses the chord is lower pitched.

**Comment by marlitas** [comment] 2024-04-01 21:30
I think we may run into a similar problem here as we are with https://github.com/phetsims/mean-share-and-balance/issues/173. The range can equal `0` and `ContinuousPropertySoundClip` is not supporting that at the moment.

**Comment by jbphet** [comment] 2024-04-17 20:51
I've implemented the initial attempt at this.  I'll assign to the sound design team to get their input.

Also, here are some things I'd like to discuss in the next review meeting:

- Should the sound really be activated when the levels are changed and the pipes are open?  That's the way it behaves in the video, so I matched that, but I'm not sure it's what we want.
- Because of the question in the previous bullet item, the sound can also be produced when adding and removing cups, which also seems a little odd.  On the other hand, it does often cause changes to the levels such that they are away from and then converge to the mean, so perhaps we *do* want it.

**Comment by amanda-phet** [comment] 2024-04-18 21:08
>Should the sound really be activated when the levels are changed and the pipes are open? That's the way it behaves in the video, so I matched that, but I'm not sure it's what we want.

I don't understand the alternative. This makes perfect sense to me! 

>Because of the question in the previous bullet item, the sound can also be produced when adding and removing cups, which also seems a little odd. On the other hand, it does often cause changes to the levels such that they are away from and then converge to the mean, so perhaps we do want it.

I love that this happens!

**Comment by jbphet** [comment] 2024-04-23 18:57
@emily-phet, @Ashton-Morris, @marlitas, and I discussed this in the 4/23/2024 sound design meeting and have some thoughts and questions.
- We made a real-time tweak to the filter algorithm which I'll commit.
- We're wondering if it even makes sense to have the water flow back into the containers the way they do now when the valves are closed, since it's a bit of an unnatural thing (and we would assume part of the learning goals).  What if the water just returns instantly to the initial state and makes only a short sound effect, such as that used by the AB switch?

Assigning to @amanda-phet for input on the 2nd bullet item above.

**Comment by amanda-phet** [comment] 2024-04-26 20:32
I really like this sound as it's working right now. I like having the water flow back to the cups and don't see the benefit of the instant return to the initial state. When the water flows back and makes the "opposite" sound it feels like the switch is two different states, not just a button that does something and a button that resets. However, I've gotten feedback that the valve open/close sounds are too subtle and sound very similar, which could definitely lead to misconceptions. So, I'm open to discussing this more.

**Comment by jbphet** [comment] 2024-04-26 21:55
I agree that the valve open/close sounds are a little too similar.  I'll set things up so that we can easily try some different sounds, and then at the next sound design meeting we can try some stock ones and decide if any of those are sufficient or have @Ashton-Morris come up with some new ones.

**Comment by marlitas** [comment] 2024-04-29 19:29
From Meeting 4/29:
- @amanda-phet suggested that what we're actually trying to sonify the Mean Absolute Deviation. Perhaps we'll use that to calculate the filters and such.
- @jbphet is also going to look at adjusting the cut off frequency based on the Mean value.
- We hope that the above changes will help distinguish between the opening and closing of pipes as well.

**Comment by marlitas** [comment] 2024-05-01 15:43
We ran out of time to talk about this in the meeting yesterday. It would be really helpful if everyone can try it out on their end and provide some feedback here so we can try to finalize before Saturday!

**Comment by marlitas** [comment] 2024-05-01 17:52
I think this sounds a lot better, especially when there are more cups added. I still feel like the initial two cup set up is too similar between open and closing. It would be really nice if it muffled as much as it does when there are more cups.

**Comment by amanda-phet** [comment] 2024-05-01 23:09
I agree with @marlitas 100%.

**Comment by jbphet** [comment] 2024-05-02 20:08
We discussed this during today's sound design meeting and concluded that it still needs some work.  Having said that, if we can't get it dialed in prior to the upcoming interviews, we could use it as is for those and continue to refine it later.

Ideas to try:
- Adjusting the Q factor (resonance) in addition to the cutoff frequency
- Using the adjustment curve in the opposite direction depending on whether the valves are open or closed so that the filtered-to-unfiltered and the unfiltered-to-filtered effects are heard more quickly
- Always make the effect work over the range of the transition.
- Overall, the goal is to hear some amount of the effect in all but the smallest changes, and definitely in the default 2-glass case.

**Comment by jbphet** [comment] 2024-05-07 19:12
I've tried several approaches to mapping the deviation from the mean for the cups to cutoff frequency values.  When I tried to use simple linear mappings, the filtered effect was always too subtle.  I decided to try a piecewise mapping with three segments as shown below.  Within the code, this function is defined by the two points in the middle area, since the two endpoints are essentially fixed.

![image](https://github.com/phetsims/mean-share-and-balance/assets/3082831/1207ae96-149b-4e14-b721-31f11308b138)

In addition to creating this mapping function, the algorithm is scaling the deviation amount versus the max possible deviation so that in almost all cases when the water is flowing, the algorithm traverses the entire range of cutoff filter frequencies.  The only time that this is *not* true is when the levels are changed with the valves open.

I'll finish this off, commit, and have the team review it to see if it's acceptable.

**Comment by jbphet** [comment] 2024-05-07 20:12
Okay sound design team, I've modified this sound based on the [feedback from the previous review session](https://github.com/phetsims/mean-share-and-balance/issues/171#issuecomment-2091467019).  The effect is now more apparent over smaller ranges and more consistent overall.  Please try it out and log your feedback, and we will discuss more in the next meeting.

As for my input on the design, I think lowering the range at which the sound is played would make it a bit nicer.  The upper ranges, which occur when the glasses have a lot of water in them, sound a bit shrill to me.  Also, I think we will ultimately want to turn it down a bit.

**Comment by Ashton-Morris** [comment] 2024-05-09 17:00
I think the effect is working as intended. I feel that it sounds good to have the increased q during those low movement times to make them stand out. But it is what people describe as "synthy" because of that.

Perhaps we could decrease the min/max ranges down so that it cant get as shrill and is always a little lower in pitch range than it is now?

**Comment by jbphet** [comment] 2024-05-14 18:24
I've adjust the range of pitches for the mean values as well as the Q, and we tweaked it a bit further during today's design meeting.  @amanda-phet requested that we have @kathy-phet check it out since she had provided some feedback on this previously.  @kathy-phet - can you please try it out and let us know what you think?

**Comment by Ashton-Morris** [comment] 2024-05-31 14:12
I think the issues might be that the filtered sound is a major chord, and since it goes up and down in pitch and is being filtered it might be unpleasant for some.

Lets try a multi octave single note in stead of a major chord and see if that fixes the issue. Here is a loop to try

[MSaBSoftSineMultiOctaveLoop.wav
MSaBSoftSineMultiOctaveLoop.mp3](https://o365coloradoedu.sharepoint.com/sites/PHYS-phet-pilot/PhET%20Files/Forms/AllItems.aspx?csf=1&web=1&e=qaXh1o&CID=a8cf7b47%2D7bc5%2D4fbf%2Db07a%2D23a5082a2412&FolderCTID=0x0120001AF96E22694A1A448A9649A49C4AC974&id=%2Fsites%2FPHYS%2Dphet%2Dpilot%2FPhET%20Files%2FPhET%20Files%2FPhET%20Sim%20Design%2FMean%5F%20Share%20and%20Balance%20HTML5%2FSounds%20and%20Sonification%2FSound%20Files)

**Comment by jbphet** [comment] 2024-06-05 21:44
I integrated the new sound from @Ashton-Morris and also thought we should try out a "flowing water" sound.  @amanda-phet, @marlitas, @kathy-phet, and I all met over Zoom to discuss, but unfortunately didn't quite reach a conclusion on which option was best.  I've committed these options and we will discuss later.

**Comment by marlitas** [comment] 2024-06-27 15:08
Confirmed with @amanda-phet that we are keeping the current sound and this issue is ready to close! Thanks all :-)

**Closed by marlitas** 2024-06-27 15:08 UTC
Labels: design:sound, status:ready-for-review
