### ISSUE TITLE
Reconsider dynamic allocation of cups and pipes.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/mean-share-and-balance#60] opened 2022-06-28 21:57 UTC
For code review #41 ...

From implementation-notes.md:

> #### Memory Management
- Dynamic Allocation:
  - All the cups and pipes are added and removed dynamically as cups are added and removed through the number spinner. 
  - Therefore, all cups and pipes must be disposed along with their links and listeners.

I would strongly reconsider this approach.  There is a well-know maximum number of cups, and it's not a large number (7).  So it would be much simpler to allocate the max cups once, then use the ones that are needed.

We went with that approach in Fourier: Making Waves for the harmonics (and amplitude sliders, etc.) after much design discussion, see https://github.com/phetsims/fourier-making-waves/issues/6.  The conclusion was that it was actually preferrable to have a fixed number of harmonics in the Studio tree, rather than onstantly-changing  groups of harmonics, sliders, etc. And it seems that the same conclusions should apply here.  (If not, I'd like to know why.)

**Comment by pixelzoom** [comment] 2022-06-28 22:04
You also would not need this involved listener in IntroModel.ts:

```
 // add/remove water cups and pipes according to number spinner
    const numberOfCupsListener = ( numberOfCups: number ) => {
//... followed by 23 more lines
```

You'd simply change visibility of cup and pipe nodes based on `numberOfCupsProperty`, and ignore irrelevant cups and pipes in the model based on `numberOfCupsProperty`.

**Comment by pixelzoom** [comment] 2022-06-28 23:56
As I said in https://github.com/phetsims/mean-share-and-balance/issues/41#issuecomment-1169396433:

> The highest-priority issue is https://github.com/phetsims/mean-share-and-balance/issues/60. The choice to do dynamic allocation of pipes and cups introduces a lot of complexity, and forces serious compromises like https://github.com/phetsims/mean-share-and-balance/issues/75.  It's also NOT the approach that PhET has used fourier-making-waves, a sim that is very similar in this regard (it has a max of 11 harmonics, while this sim has a max of 7 water cups.). Perhaps the difference in approach is that @amanda-phet is the designer for this sim, which @arouinfar was the designer for fourier-making-waves.  But I would seriously reconsider this decision before proceeding further with implementation of this sim.

So raising the priority of this issue to high.

**Comment by kathy-phet** [comment] 2022-06-29 00:15
@amanda-phet and @samreid are both out this week. Let's plan to discuss early week of July 5th, when both are back in town. Does that work @marlitas?

**Comment by pixelzoom** [comment] 2022-06-29 00:18
Thinking about how to proceed with this issue, my recommendation is (in this order):

(1) Have the MSAB team take a look at FMW in Studio, to review how we addressed a variable number of harmonics.  Looking at the Discrete screen subtree should be sufficient. Here are the important elements, where '*' can be replaced with a number in the range [1,11]:
 
`fourierMakingWaves.discreteScreen.model.fourierSeries.numberOfHarmonicsProperty`
`fourierMakingWaves.discreteScreen.model.fourierSeries.harmonics.harmonic*`
`fourierMakingWaves.discreteScreen.view.charts.amplitudes.amplitudesChartNode.amplitude*NumberDisplay`
`fourierMakingWaves.discreteScreen.view.charts.amplitudes.amplitudesChartNode.amplitude*Slider`

(2) Have a design meeting that includes the MSAB and FMW teams: @amanda-phet, @marlitas, @samreid, @kathy-phet, @arouinfar, and me.  Review what we did (and why) in FMW. Decide whether that's a good/better fit for MSAB. Discuss whether consistency of approaches between sims is a PhET goal. Etc.

**Comment by kathy-phet** [comment] 2022-06-29 00:25
This is helpful, Chris. Thanks for bringing up the notion of consistency across sims with PhET-iO approach, too. Defintely useful to consider for client experience.

**Comment by samreid** [comment] 2022-07-05 23:24
Today @marlitas @arouinfar @kathy-phet @amanda-phet @pixelzoom and @zepumph and myself @samreid met to discuss this topic.  

The general consensus was that PhetioGroup is essential and important for NaturalSelection and Circuit Construction Kit.  They have a large number of non-reused items.

We decided we wanted to try statically allocating the 2d cups, 3d cups and pipes for this simulation for the following reasons:
* The studio tree interface will be acceptable.  In other sims such as Geometric Optics, there are items in the tree that are not shown in the sim and that is ok.  We want to make this a normal part of our process.
* There is a small number of reusable items
* The implementation/complexity will go down significantly

We demonstrated that indices in PhetioGroup can be reused if you decrement `groupElementIndex` in disposeElement.  However, that is not desirable for Circuit Construction Kit or Natural Selection which should have incrementing non-reused indices.  One day we may want to have an option in PhetioGroup that lets you select whether indices would be reused or not.

We discussed ways to hide the non-active elements from the studio tree.  We will not be taking action on any of these ideas now.
* Hiding items that are non-active
* Strikethrough items that are non-active
* A hidden-eye icon next to tree items that are non-active.

@zepumph also asked the question about why the cost to use PhetioGroup was high.  I feel like numerous tiny errors accumulated quickly. Each error was solved in 30-60 minutes and so didn't seem like that much of a problem in itself (hence did not leave a paper trail), but the fact that we hit maybe 10 problems like that led to the overall costs.  Without analyzing the commit history and reflecting, I'm not sure I could identify those problems specifically.

@pixelzoom can you please review and see if I missed any important details?

**Comment by pixelzoom** [comment] 2022-07-05 23:30
Thanks @samreid, excellent summary.

**Comment by marlitas** [comment] 2022-07-06 18:51
Beginning to switch dynamic allocation to static allocation. Certain this will cause testing errors in CT. Will address as quickly and thoroughly as possible, while chipping away at this change.

**Comment by samreid** [comment] 2022-08-22 16:58
All known problems moved to side issue, everything else looks great here. Nice work @marlitas! We recommend @pixelzoom re-review significant changes like this, but it's not clear whether we should do that one-at-a-time or wait until we are closer to the RC.  @pixelzoom what do you recommend?

**Comment by pixelzoom** [comment] 2022-08-22 17:45
There's a duplicate phetioID that's preventing this sim from loading in Studio:

```
Assertion failed:  phetioID already registered: meanShareAndBalance.introScreen.view.ValveNode
assert.js:28 Uncaught Error: Assertion failed: phetioID already registered: meanShareAndBalance.introScreen.view.ValveNode
    at window.assertions.assertFunction (assert.js:28:13)
    at PhetioEngine.phetioObjectAdded (phetioEngine.ts:658:36)
    at Object.addPhetioObject (phetioEngine.ts:1223:20)
    at Tandem.addPhetioObject (Tandem.ts:196:38)
    at ValveNode.initializePhetioObject (PhetioObject.ts:335:17)
    at ValveNode.initializePhetioObject (Node.ts:6321:11)
    at ValveNode.mutate (Node.ts:6311:10)
    at new Node (Node.ts:825:12)
    at new ValveNode (ValveNode.ts:53:5)
    at new IntroScreenView (IntroScreenView.ts:124:13)
```

So I can't proceed with review of this issue. Please assign back to me when it's fixed.

**Comment by marlitas** [comment] 2022-08-22 17:50
Fixed! Assigning back to @pixelzoom

**Comment by pixelzoom** [comment] 2022-08-22 18:00
I skimmed the commits and played with the sim in Studio. This all looks very nice.   

One question... Has the PhET-iO designer (@amanda-phet?) been consulted about whether to use zero-based numbering for cups and pipes? You're currently using zero-based numbering, where "the first cup" is `waterCup2D0`.    Cups and pipes are not numbered in the UI, so this may be OK.  But it's worthing checking with the designer.

In Fourier, we used 1-based numbering. But that was driven by the fact that harmonics are numbered 1...N in the UI.

**Comment by marlitas** [comment] 2022-08-22 19:03
> Has the PhET-iO designer (@amanda-phet?) been consulted about whether to use zero-based numbering for tandems associated with cups and pipes?

This has not been solidified by design. I believe it was briefly mentioned in the dynamic vs. static meeting about using zero-based numbering, but I don't have documentation to confirm. Assigning to @amanda-phet to get feedback.

**Comment by pixelzoom** [comment] 2022-08-22 20:11
Also noting that whether to prefer zero-based vs one-based numbering in PhET-iO tandem names may be a more general discussion.  It may be related to who we think the instructional designers will be, and whether they can "think like a programmer" (zero-based) or not (one-based).   And of course their will be sim-specific cases (like Fourier) where tandem numbering should presumably match UI numbering, regardless of what the PhET convention is.

**Comment by kathy-phet** [comment] 2022-08-22 20:12
@JacquiHayes - Feel free to put on your "instructional designer" hat and comment on numbering in PhET-iO groups in general.

**Comment by JacquiHayes** [comment] 2022-08-23 02:41
In static cases, where you have a small number of elements to be named, I feel like the numbers should match the natural numbers (one-based). Cup 1 to Cup 7.

Generally, I assume that our IDs are using platforms that already have a numbering system in play.

For some platforms, the developers will have created zero-based numbering systems, others would have converted their numbering system to one-based. To be pragmatic about it, I assume it is easier for IDs who are using a zero-based to use a one-based system than for an ID who has never heard of a zero-based to learn it.

**Comment by samreid** [comment] 2022-08-23 17:20
We agreed months ago to use 0-based indexing unless there is a special case where there is a domain-specific constraint (such as in Fourier). However, (a) I could not find a paper trail for that decision and (b) it could be that we now want to overturn that decision. Perhaps @zepumph knows more?  Maybe best to chat in an upcoming zoom meeting since it seems there is disagreement here.

**Comment by pixelzoom** [comment] 2022-08-23 17:30
If a convention was established, this developer is not aware of it, and can find no documentation.  So I thought it was worth discussing. I also think that the convention that should be set by non-programmers, because programmers (incorrectly) think that non-programmers understand 0-based numbering.

**Comment by amanda-phet** [comment] 2022-08-26 15:55
I thought we decided we were ok with 0-based indexing, too. We use it in Natural Selection for the bunnies (something like bunny_0), but maybe in that case it makes sense because it's the "initial" bunny. In this case we are talking about such a small number of cups that maybe we should move ahead with using natural numbers 1-7 for the cups.

**Comment by pixelzoom** [comment] 2022-08-26 16:45
In Natural Selection, bunnies are created dynamically.  They are not numbered in the UI, and clients are unlikely to ever inspect the elements under `model.bunnyCollection` in Studio.  So the numbering is unimportant, and we used 0-based numbering (which is sort of the default when you're programming :)

In Fourier, we used 1-based numbering because the harminonics are specifically numbered in the UI. I.e., A<sub>1</sub>, A<sub>2</sub>, etc.

In MSAB, cups and pipes are not explicitly numbered in the UI.  But this sim does seem to be more aligned with Fourier, in that IDs (and teachers, students?) are likely to refer to "the first cup", "the second cup", etc. 

So yes, we did decide to default to 0-based indexing. But we also decided to uses 1-based indexing where it's a better match. And that's why this issue was opened.

**Comment by amanda-phet** [comment] 2022-08-29 16:12
Let's use 1-based numbering for the cups/plates etc. in this sim.

**Comment by marlitas** [comment] 2022-09-06 17:04
All indexing is now 1-based for PhET-iO. Sending back to @amanda-phet  and @pixelzoom  for review and feedback.

**Comment by pixelzoom** [comment] 2022-09-06 17:07
I inspected the Studio tree. It looks great to me!

**Comment by marlitas** [comment] 2022-10-28 15:26
The changes in this issue have been applied for a while with no additional feedback. Therefore, closing as completed.

**Closed by marlitas** 2022-10-28 15:26 UTC
Labels: design:phet-io, dev:code-review, dev:phet-io, status:ready-for-review
