### ISSUE TITLE
Blurry cup outlines when zoomed out

### ISSUE THREAD

**Issue by stemilymill** [phetsims/mean-share-and-balance#112] opened 2022-09-19 16:47 UTC
For https://github.com/phetsims/qa/issues/835

Observed on multiple devices.

When the sim is zoomed out, the outlines of the 3d cups seem blurry/pixelated, being most obvious on the cup rim. This remained the same when I changed the window size. When zoomed in, the cup outlines are very crisp.

Visuals

Blurry when zoomed out
![3d cups blurry lines](https://user-images.githubusercontent.com/85511101/191069937-6578f402-1d70-458c-95a9-4a15293a4a0c.jpg)

Not blurry when zoomed in
![not blurry zoomed in](https://user-images.githubusercontent.com/85511101/191068255-decb1f04-3892-48fc-9b78-57a0ead0f803.jpg)

I remember something similar happening in Number Line Distance, and I think the solution involved mipmaps, but I could also be totally mistaken..

<details><summary>details</summary>
<p>

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Mean: Share and Balance‬
URL: https://phet-dev.colorado.edu/html/mean-share-and-balance/1.0.0-dev.8/phet/mean-share-and-balance_all_phet.html
Version: 1.0.0-dev.8 2022-09-16 20:09:53 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Language: en-US
Window: 1493x775
Pixel Ratio: 1.125/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</p>
</details>

**Comment by marlitas** [comment] 2022-10-07 15:30
This is caused by aliasing by the browser. We are already using SVG, and @samreid and I don't think there is anything we can or should do about this. We tried `renderer: 'canvas'` and it looks about the same. We do not want to use a png ( or mipmaps ) to render these, because it is preferable to use code and vector graphics. Perhaps one day browsers will do better at anti-aliasing and rendering curves. We can only hope. Closing.

**Closed by marlitas** 2022-10-07 15:30 UTC
Labels: type:bug
